/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 13:01:45 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = WordUtils.wrap("java.vm.specification.name", 2, (String) null, true);
      assertEquals("ja\nva\n.v\nm.\nsp\nec\nif\nic\nat\nio\nn.\nna\nme", string0); // (Primitive) Original Value: ja va .v m. sp ec if ic at io n. na me | Regression Value: jav a.v m.s pec ifi cat ion .na me
  }
}
