/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 12:50:16 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = "6v025O*:T";
      String string1 = WordUtils.wrap("6v025O*:T", 2, "iLi}HzKHF6L}", true);
      assertEquals("6viLi}HzKHF6L}02iLi}HzKHF6L}5OiLi}HzKHF6L}*:iLi}HzKHF6L}T", string1); // (Primitive) Original Value: 6viLi}HzKHF6L}02iLi}HzKHF6L}5OiLi}HzKHF6L}*:iLi}HzKHF6L}T | Regression Value: 6v025O*:T
      assertFalse(string1.equals((Object)string0));
  }
}
