/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 13:35:34 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = WordUtils.wrap("Windows 9", (-290), (String) null, true);
      assertEquals("W\ni\nn\nd\no\nw\ns\n9", string0); // (Primitive) Original Value: W i n d o w s 9 | Regression Value: W nd ws 9
  }
}
