/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 14:17:35 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      // Undeclared exception!
      try { 
        WordUtils.abbreviate(" ", (-2070), (-1403), " ");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = WordUtils.abbreviate("L-5(BSA<+CO ?/';", 0, (-1), "");
      assertEquals("L-5(BSA<+CO", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = WordUtils.abbreviate("V'-mWa`J9qBurZT", (-1195), 1, "");
      assertEquals("V", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = WordUtils.abbreviate("#}q)oK# I)iD1zi`/d", (-2470), 7, "R");
      assertEquals("#}q)oK#R", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = WordUtils.abbreviate("5.0", 3, 3, "OCk#c]]H6KrCk#c]]H6KgCk#c]]H6K.Ck#c]]H6KaCk#c]]H6KpCk#c]]H6KaCk#c]]H6KcCk#c]]H6KhCk#c]]H6KeCk#c]]H6K.Ck#c]]H6KcCk#c]]H6KoCk#c]]H6KmCk#c]]H6KmCk#c]]H6KoCk#c]]H6KnCk#c]]H6KsCk#c]]H6K.Ck#c]]H6KlCk#c]]H6KaCk#c]]H6KnCk#c]]H6KgCk#c]]H6K.Ck#c]]H6KWCk#c]]H6KoCk#c]]H6KrCk#c]]H6KdCk#c]]H6KUCk#c]]H6KtCk#c]]H6KiCk#c]]H6KlCk#c]]H6Ks");
      assertEquals("5.0", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      char[] charArray0 = new char[3];
      String string0 = WordUtils.capitalizeFully("9v2a^`$:;", charArray0);
      assertEquals("9v2a^`$:;", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = WordUtils.wrap("NJ,\n5d$", 0, "file.encoding", true);
      assertEquals("Nfile.encodingJfile.encoding,file.encoding\nfile.encoding5file.encodingdfile.encoding$", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = WordUtils.wrap("", 48);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String string0 = WordUtils.uncapitalize((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = WordUtils.uncapitalize("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = WordUtils.initials("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String string0 = WordUtils.capitalizeFully((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String string0 = WordUtils.capitalizeFully("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String string0 = WordUtils.capitalize((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String string0 = WordUtils.capitalize("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      String string0 = WordUtils.initials("user.region", (char[]) null);
      assertEquals("u", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      char[] charArray0 = new char[3];
      String string0 = WordUtils.initials((String) null, charArray0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      char[] charArray0 = new char[5];
      charArray0[2] = 'c';
      String string0 = WordUtils.uncapitalize("org.apache.commons.lang.WordUtils", charArray0);
      assertEquals("org.apache.commons.lang.WordUtils", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      String string0 = WordUtils.uncapitalize("Sf,\"lh*f|oxbla", (char[]) null);
      assertEquals("sf,\"lh*f|oxbla", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      String string0 = WordUtils.capitalizeFully("Sf,\"lh*F|OxbLa", (char[]) null);
      assertEquals("Sf,\"lh*f|oxbla", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      char[] charArray0 = new char[5];
      charArray0[2] = 'c';
      String string0 = WordUtils.capitalize("oCk#c]]H6KrCk#c]]H6KgCk#c]]H6K.Ck#c]]H6KaCk#c]]H6KpCk#c]]H6KaCk#c]]H6KcCk#c]]H6KhCk#c]]H6KeCk#c]]H6K.Ck#c]]H6KcCk#c]]H6KoCk#c]]H6KmCk#c]]H6KmCk#c]]H6KoCk#c]]H6KnCk#c]]H6KsCk#c]]H6K.Ck#c]]H6KlCk#c]]H6KaCk#c]]H6KnCk#c]]H6KgCk#c]]H6K.Ck#c]]H6KWCk#c]]H6KoCk#c]]H6KrCk#c]]H6KdCk#c]]H6KUCk#c]]H6KtCk#c]]H6KiCk#c]]H6KlCk#c]]H6Ks", charArray0);
      assertEquals("OCk#c]]H6KrCk#c]]H6KgCk#c]]H6K.Ck#c]]H6KaCk#c]]H6KpCk#c]]H6KaCk#c]]H6KcCk#c]]H6KhCk#c]]H6KeCk#c]]H6K.Ck#c]]H6KcCk#c]]H6KoCk#c]]H6KmCk#c]]H6KmCk#c]]H6KoCk#c]]H6KnCk#c]]H6KsCk#c]]H6K.Ck#c]]H6KlCk#c]]H6KaCk#c]]H6KnCk#c]]H6KgCk#c]]H6K.Ck#c]]H6KWCk#c]]H6KoCk#c]]H6KrCk#c]]H6KdCk#c]]H6KUCk#c]]H6KtCk#c]]H6KiCk#c]]H6KlCk#c]]H6Ks", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      String string0 = WordUtils.wrap("hPs7$v, e@8y", 0, "hPs7$v, e@8y", false);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      String string0 = WordUtils.wrap(" gb", (-995), "", false);
      assertEquals("gb", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      String string0 = WordUtils.wrap("7}<=N_iS_", (-1793), (String) null, true);
      assertEquals("7\n}\n<\n=\nN\n_\ni\nS\n_", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      String string0 = WordUtils.wrap((String) null, (-1), "java.ext.dirs", false);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      String string0 = WordUtils.abbreviate("UE'vdV\t*f7W 0G=d", 2, 0, "x7vH*\roAu2$7vH*\roAu2t7vH*\roAu2[7vH*\roAu2q7vH*\roAu2C7vH*\roAu2t7vH*\roAu267vH*\roAu297vH*\roAu2V7vH*\roAu2%7vH*\roAu2{7vH*\roAu2Q");
      assertEquals("UEx7vH*\roAu2$7vH*\roAu2t7vH*\roAu2[7vH*\roAu2q7vH*\roAu2C7vH*\roAu2t7vH*\roAu267vH*\roAu297vH*\roAu2V7vH*\roAu2%7vH*\roAu2{7vH*\roAu2Q", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      String string0 = WordUtils.abbreviate("\"+`_zh;", 4418, (-1), "\"+`_zh;");
      assertEquals("\"+`_zh;", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      String string0 = WordUtils.abbreviate("java.vendor", '`', 48, "org.apache.commons.lang.WordUtils");
      assertEquals("java.vendor", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      String string0 = WordUtils.abbreviate((String) null, 0, 0, ",1hSly");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      String string0 = WordUtils.abbreviate("", 0, 0, " ");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      char[] charArray0 = new char[8];
      charArray0[0] = ')';
      String string0 = WordUtils.initials("^,s<(Ar\ntl<)p\"t", charArray0);
      assertEquals("^p", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      char[] charArray0 = new char[0];
      String string0 = WordUtils.initials(",1hSly", charArray0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      String string0 = WordUtils.initials(".?j6PM_pZO9s[L.s");
      assertEquals(".", string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      String string0 = WordUtils.initials("", (char[]) null);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      String string0 = WordUtils.swapCase("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      String string0 = WordUtils.swapCase("^,s<(Ar\ntl<)p\"t");
      assertEquals("^,S<(aR\nTL<)P\"T", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      String string0 = WordUtils.swapCase((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      char[] charArray0 = new char[0];
      String string0 = WordUtils.uncapitalize("", charArray0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      char[] charArray0 = new char[1];
      String string0 = WordUtils.uncapitalize((String) null, charArray0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      char[] charArray0 = new char[0];
      String string0 = WordUtils.uncapitalize(",1hSly", charArray0);
      assertEquals(",1hSly", string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      char[] charArray0 = new char[0];
      String string0 = WordUtils.capitalizeFully(",1hSly", charArray0);
      assertEquals(",1hSly", string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      char[] charArray0 = new char[8];
      String string0 = WordUtils.capitalizeFully("", charArray0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      char[] charArray0 = new char[8];
      String string0 = WordUtils.capitalizeFully((String) null, charArray0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      String string0 = WordUtils.capitalizeFully("^,s<(Ar  tl<)p\"t");
      assertEquals("^,s<(ar  Tl<)p\"t", string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      char[] charArray0 = new char[0];
      String string0 = WordUtils.capitalize("\"+`_zh;", charArray0);
      assertEquals("\"+`_zh;", string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      String string0 = WordUtils.capitalize("", (char[]) null);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      char[] charArray0 = new char[4];
      String string0 = WordUtils.capitalize((String) null, charArray0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      String string0 = WordUtils.wrap("x$t[qCt 69V%{Q", 0, "7vH*\roAu2", true);
      assertEquals("x7vH*\roAu2$7vH*\roAu2t7vH*\roAu2[7vH*\roAu2q7vH*\roAu2C7vH*\roAu2t7vH*\roAu267vH*\roAu297vH*\roAu2V7vH*\roAu2%7vH*\roAu2{7vH*\roAu2Q", string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      String string0 = WordUtils.wrap("", 48, "", true);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      String string0 = WordUtils.wrap((String) null, (-458));
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      WordUtils wordUtils0 = new WordUtils();
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      String string0 = WordUtils.uncapitalize("^,S<(aR\nTL<)P\"T");
      assertEquals("^,S<(aR\ntL<)P\"T", string0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      String string0 = WordUtils.wrap("^,s<(Ar  tl<)p\"t", 0);
      assertEquals("^,s<(Ar\ntl<)p\"t", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      String string0 = WordUtils.initials((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      String string0 = WordUtils.capitalize("*51(f6");
      assertEquals("*51(f6", string0);
  }
}
