/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 13:17:34 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = ".U}9S.";
      String string1 = WordUtils.wrap(".U}9S.", (-3419));
      assertEquals(".U}9S.", string1); // (Primitive) Original Value: .U}9S. | Regression Value: U}9S.
      assertTrue(string1.equals((Object)string0));
  }
}
