/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 14:17:43 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // EXCEPTION DIFF:
      // The original version did not exhibit this exception:
      //     java.lang.StringIndexOutOfBoundsException : String index out of range: -1
      WordUtils.wrap("77!03-UA", (-2168), "f'c,\"MPd&K0%~.*@xZ", false);
      // EXCEPTION DIFF:
      // The modified version did not exhibit this exception:
      //     java.lang.StringIndexOutOfBoundsException : String index out of range: -1015
      // Undeclared exception!
      try { 
        WordUtils.abbreviate("f,v|~{x~n?#U\"|J", (-1015), (-1365), "hP-UX");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
         assertTrue(e.getMessage().equals("String index out of range: -1015"));   
      }
  }
}
