/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 13:08:57 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = WordUtils.wrap(".aY", (-4889), "q$M3`YC-$:-`wN", true);
      assertEquals(".q$M3`YC-$:-`wNaq$M3`YC-$:-`wNY", string0); // (Primitive) Original Value: .q$M3`YC-$:-`wNaq$M3`YC-$:-`wNY | Regression Value: .aq$M3`YC-$:-`wNY
  }
}
