/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 12:51:12 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // EXCEPTION DIFF:
      // The original version did not exhibit this exception:
      //     java.lang.ArithmeticException : / by zero
      WordUtils.wrap("java.runtime.version", 0, "", false);
      // EXCEPTION DIFF:
      // The modified version did not exhibit this exception:
      //     java.lang.StringIndexOutOfBoundsException : String index out of range: -142
      // Undeclared exception!
      try { 
        WordUtils.abbreviate("TDyt,I%x3lJ.NOqU/.", (-142), (-142), "TDyt,I%x3lJ.NOqU/.");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
         assertTrue(e.getMessage().equals("String index out of range: -142"));   
      }
  }
}
