/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 13:17:05 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = WordUtils.wrap(" is less than 0: ", (-2992), "user.home", true);
      assertEquals("iuser.homesuser.homeluser.homeeuser.homesuser.homesuser.hometuser.homehuser.homeauser.homenuser.home0user.home:user.home", string0); // (Primitive) Original Value: iuser.homesuser.homeluser.homeeuser.homesuser.homesuser.hometuser.homehuser.homeauser.homenuser.home0user.home:user.home | Regression Value: iuser.homeuser.homeluser.homeeuser.homesuser.homeuser.hometuser.homehuser.homeauser.homeuser.home0user.homeuser.home 
  }
}
