/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 13:06:03 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = WordUtils.wrap("Org.apache.commons.lang.wordutils", (-1764), " ", true);
      assertEquals("O r g . a p a c h e . c o m m o n s . l a n g . w o r d u t i l s", string0); // (Primitive) Original Value: O r g . a p a c h e . c o m m o n s . l a n g . w o r d u t i l s | Regression Value: r . p c e c m o s l n . o d t l s
  }
}
