/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 13:05:45 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = WordUtils.wrap("M9ZSIqR0l", 0, "3FE57gp<yl[]gx\"uN", true);
      assertEquals("M3FE57gp<yl[]gx\"uN93FE57gp<yl[]gx\"uNZ3FE57gp<yl[]gx\"uNS3FE57gp<yl[]gx\"uNI3FE57gp<yl[]gx\"uNq3FE57gp<yl[]gx\"uNR3FE57gp<yl[]gx\"uN03FE57gp<yl[]gx\"uNl", string0); // (Primitive) Original Value: M3FE57gp<yl[]gx"uN93FE57gp<yl[]gx"uNZ3FE57gp<yl[]gx"uNS3FE57gp<yl[]gx"uNI3FE57gp<yl[]gx"uNq3FE57gp<yl[]gx"uNR3FE57gp<yl[]gx"uN03FE57gp<yl[]gx"uNl | Regression Value: M93FE57gp<yl[]gx"uNZSI3FE57gp<yl[]gx"uNqR0l3FE57gp<yl[]gx"uN
  }
}
