/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 13:05:05 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = WordUtils.wrap(">11qD -aFsbr|evYP1", (-3378), (String) null, true);
      assertEquals(">\n1\n1\nq\nD\n-\na\nF\ns\nb\nr\n|\ne\nv\nY\nP\n1", string0); // (Primitive) Original Value: > 1 1 q D - a F s b r | e v Y P 1 | Regression Value: > 1 1 q D - a F sbr|evYP1
  }
}
