/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 13:01:55 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = WordUtils.wrap("paE-x'lM4MC#iIDrjb", 3, "org.apache.commons.lang.WordUtils", true);
      assertEquals("paEorg.apache.commons.lang.WordUtils-x'org.apache.commons.lang.WordUtilslM4org.apache.commons.lang.WordUtilsMC#org.apache.commons.lang.WordUtilsiIDorg.apache.commons.lang.WordUtilsrjb", string0); // (Primitive) Original Value: paEorg.apache.commons.lang.WordUtils-x'org.apache.commons.lang.WordUtilslM4org.apache.commons.lang.WordUtilsMC#org.apache.commons.lang.WordUtilsiIDorg.apache.commons.lang.WordUtilsrjb | Regression Value: paorg.apache.commons.lang.WordUtilsE-org.apache.commons.lang.WordUtilsx'org.apache.commons.lang.WordUtilslMorg.apache.commons.lang.WordUtils4Morg.apache.commons.lang.WordUtilsC#org.apache.commons.lang.WordUtilsiIorg.apache.commons.lang.WordUtilsDrorg.apache.commons.lang.WordUtilsjb
  }
}
