/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 14:08:54 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = WordUtils.wrap("{e^}pz_ qR?y", (-1), "a;{Xz(}l", true);
      assertEquals("{a;{Xz(}lea;{Xz(}l^a;{Xz(}l}a;{Xz(}lpa;{Xz(}lza;{Xz(}l_a;{Xz(}lqa;{Xz(}lRa;{Xz(}l?a;{Xz(}ly", string0); // (Primitive) Original Value: {a;{Xz(}lea;{Xz(}l^a;{Xz(}l}a;{Xz(}lpa;{Xz(}lza;{Xz(}l_a;{Xz(}lqa;{Xz(}lRa;{Xz(}l?a;{Xz(}ly | Regression Value: { e ^ } p z _ q R ? y
  }
}
