/*
 * This file was automatically generated by EvoSuite
 * Sun May 05 01:12:56 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball((-2844L), 1, 0, "=CC", "l%M", (String) null, ", firstPollOffsetStrategy=", ", firstPollOffsetStrategy=", "KafkaSpoutConfig{kafkaProps=", "", "1,", "");
      String string0 = ball0.getFinalString();
      assertEquals("KafkaSpoutConfig{kafkaProps=, firstPollOffsetStrategy=, keyDeserializer=KafkaSpoutConfig{kafkaProps=, valueDeserializer=, pollTimeoutMs=, offsetCommitPeriodMs=-2844, maxRetries=1, maxUncommittedOffsets=0, firstPollOffsetStrategy==CC, kafkaSpoutStreams=l%M, tuplesBuilder=null, retryService=, firstPollOffsetStrategy=, topics=1,, topicWildcardPattern=}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps=, firstPollOffsetStrategy=, keyDeserializer=KafkaSpoutConfig{kafkaProps=, valueDeserializer=, pollTimeoutMs=, offsetCommitPeriodMs=-2844, maxRetries=1, maxUncommittedOffsets=0, firstPollOffsetStrategy==CC, kafkaSpoutStreams=l%M, tuplesBuilder=null, retryService=, firstPollOffsetStrategy=, topics=1,, topicWildcardPattern=} | Regression Value: KafkaSpoutConfig{kafkaProps=, firstPollOffsetStrategy=, keyDeserializer=KafkaSpoutConfig{kafkaProps=, valueDeserializer=, pollTimeoutMs=, offsetCommitPeriodMs=-2844, maxUncommittedOffsets=0, firstPollOffsetStrategy==CC, kafkaSpoutStreams=l%M, tuplesBuilder=null, retryService=, firstPollOffsetStrategy=, topics=1,, topicWildcardPattern=}
  }
}
