/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 14:09:43 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = WordUtils.wrap("l^ksEiBG", 0, "l^ksEiBG", true);
      assertEquals("ll^ksEiBG^l^ksEiBGkl^ksEiBGsl^ksEiBGl^ksEiBGEl^ksEiBGil^ksEiBGBl^ksEiBGG", string0); // (Primitive) Original Value: ll^ksEiBG^l^ksEiBGkl^ksEiBGsl^ksEiBGl^ksEiBGEl^ksEiBGil^ksEiBGBl^ksEiBGG | Regression Value: G
  }
}
