/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 13:38:18 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = "L3I<+`r1!r$";
      String string1 = WordUtils.wrap("L3I<+`r1!r$", 1, "", true);
      assertEquals("L3I<+`r1!r$", string1); // (Primitive) Original Value: L3I<+`r1!r$ | Regression Value: LI+r!$
      assertTrue(string1.equals((Object)string0));
  }
}
