/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 13:41:00 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = WordUtils.wrap("Windows NT", (-507));
      assertEquals("Windows\nNT", string0); // (Primitive) Original Value: Windows NT | Regression Value: Windows  T
      
      // EXCEPTION DIFF:
      // The original version did not exhibit this exception:
      //     java.lang.StringIndexOutOfBoundsException : String index out of range: -1
      WordUtils.wrap("YPI*kD&{WXSk ", (-507));
      // EXCEPTION DIFF:
      // The modified version did not exhibit this exception:
      //     java.lang.StringIndexOutOfBoundsException : String index out of range: -507
      // Undeclared exception!
      try { 
        WordUtils.abbreviate("org.apache.commons.lang.WordUtils", (-507), (-507), "s=91eBy. w']!7#");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
         assertTrue(e.getMessage().equals("String index out of range: -507"));   
      }
  }
}
