/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 16 14:31:07 GMT 2019
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // EXCEPTION DIFF:
      // The original version did not exhibit this exception:
      //     org.evosuite.runtime.TooManyResourcesException : Loop has been executed more times than the allowed 10000
      WordUtils.wrap("usKwlA", (-578), "FAx7~}PJzP<m", true);
      // EXCEPTION DIFF:
      // The modified version did not exhibit this exception:
      //     java.lang.StringIndexOutOfBoundsException : String index out of range: -578
      // Undeclared exception!
      try { 
        WordUtils.abbreviate("usKwlA", (-1603), (-578), "Minimum abbreviation width is 4");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
         assertTrue(e.getMessage().equals("String index out of range: -578"));   
      }
  }
}
